export const data = [
  {
    id: 1,
    desc: "These are not your average taco truck tacos. We make ours with love. Try one today!",
    src: "sauce.jpg",
    alt: "taco",
    width: "1272",
    height: "1920",
    footerName: "Loco's Burritos'",
    footerPrice: "$4.75",
  },
  {
    id: 2,
    desc: "Can you say Buuuurrrrito? Our Burritoes are full of the best ingredients. Get yours while we still have them. ",
    src: "tacovert1.jpg",
    alt: "taco",
    width: "1250",
    height: "1875",
    footerName: "Loco's Tacos'",
    footerPrice: "$4.75",
  },
  {
    id: 3,
    desc: "Sip Something Saturday Sangrias. You can thank us later. Refreshing!",
    src: "drinksvert.jpg",
    alt: "taco",
    width: "3839",
    height: "5759",
    footerName: "Sip Something",
    footerPrice: "$3.50",
  },
];

export const items = [
  {
    id: 1,
    title: "pancakes",
    category: "breakfast",
    price: 15.99,
    img: "taco1.jpeg",
    width: "100%",
    height: "100%",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    btnType: "secondaryBtn",
  },
  {
    id: 2,
    title: "double",
    category: "lunch",
    price: 13.99,
    img: "taco1.jpeg",
    width: "600",
    height: "600",
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    btnType: "tertiaryBtn",
  },
  {
    id: 3,
    title: "milkshake",
    category: "lunch",
    price: 6.99,
    img: "taco1.jpeg",
    width: "100%",
    height: "100%",
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    btnType: "tertiaryBtn",
  },
  {
    id: 4,
    title: "delight",
    category: "breakfast",
    price: 20.99,
    img: "taco1.jpeg",
    width: "100%",
    height: "100%",
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    btnType: "secondaryBtn",
  },
  {
    id: 5,
    title: "attack",
    category: "lunch",
    price: 22.99,
    img: "taco1.jpeg",
    width: "100%",
    height: "100%",
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    btnType: "tertiaryBtn",
  },
  {
    id: 6,
    title: "dream",
    category: "lunch",
    price: 18.99,
    img: "taco1.jpeg",
    width: "100%",
    height: "100%",
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    btnType: "tertiaryBtn",
  },
  {
    id: 7,
    title: "overflow",
    category: "breakfast",
    price: 8.99,
    img: "taco1.jpeg",
    width: "100%",
    height: "100%",
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    btnType: "secondaryBtn",
  },
  {
    id: 8,
    title: "classic",
    category: "lunch",
    price: 12.99,
    img: "taco1.jpeg",
    width: "100%",
    height: "100%",
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    btnType: "tertiaryBtn",
  },
  {
    id: 9,
    title: "buddy",
    category: "lunch",
    price: 16.99,
    img: "taco1.jpeg",
    width: "100%",
    height: "100%",
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    btnType: "",
  },
];
