import React, { useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Navbar from "../src/components/Navbar";
import Hero from "../src/components/Hero";
import About from "../src/components/About";
import Specialties from "../src/components/Specialties";
import { data } from "../data";
import MenuPage from "../src/components/MenuPage";
import Contact from "../src/components/Contact";
import Newsletter from "../src/components/Newsletter";
import Footer from "../src/components/Footer";
import MenuPageCont from "../src/components/MenuPageCont";

import { createClient } from "contentful";


export default function Home({ specialties, menuItems }) {
  console.log(menuItems);
  return (
    <>
      <div className={styles.homeBgColor}>
        <div className={styles.container}>
          <Head>
            <title>Taco Bell</title>
            <meta name='description' content='Generated by create next app' />
            <link rel='icon' href='/favicon.ico' />
          </Head>
          <Navbar />
          <Hero />
          <About />
          <Specialties specialties={specialties} />
          <MenuPage />
          <Contact />
          <Newsletter />
          <MenuPageCont />
          <Footer />
        </div>
      </div>
    </>
  );
}

export async function getStaticProps() {
  const specialties = data;
  const client = createClient({
    space: process.env.CONTENTFUL_SPACE_ID,
    accessToken: process.env.CONTENTFUL_ACCESS_KEY,
  });
  const res = await client.getEntries({ content_type: "menuItem" });

  return {
    props: {
      menuItems: res.items,
      specialties,
    },
  };
}


