import React, { useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Navbar from "../src/components/Navbar";
import Hero from "../src/components/Hero";
import About from "../src/components/About";
import Specialties from "../src/components/Specialties";
import { data } from "../data";
import Menu from "../src/components/Menu";


export default function Home({ specialties }) {


  return (
    <>
      <div className={styles.homeBgColor}>
        <div className={styles.container}>
          <Head>
            <title>Create Next App</title>
            <meta name='description' content='Generated by create next app' />
            <link rel='icon' href='/favicon.ico' />
          </Head>
          <Navbar />
          <Hero />
          <About />
          <Specialties specialties={specialties} />
          <Menu />
        </div>
      </div>
    </>
  );
}

export const getStaticProps = () => {
  const specialties = data;
  return {
    props: { specialties },
  };
};
